import scipy.stats as stats
import matplotlib.pyplot as plt
import numpy as np
from helper import *
'''
data = getData('distA.csv')
stats.probplot(data, dist = 'norm', plot=plt)
plt.savefig("distA-norm.png")
stats.probplot(data, dist = 'cauchy', plot=plt)
plt.savefig("distA-cauchy.png")
stats.probplot(data, dist = 'cosine', plot=plt)
plt.savefig("distA-cosine.png")
stats.probplot(data, dist = 'expon', plot=plt)
plt.savefig("distA-expon.png")
stats.probplot(data, dist = 'uniform', plot=plt)
plt.savefig("distA-uniform.png")
stats.probplot(data, dist = 'laplace', plot=plt)
plt.savefig("distA-laplace.png")
stats.probplot(data, dist = 'wald', plot=plt)
plt.savefig("distA-wald.png")
stats.probplot(data, dist = 'rayleigh', plot=plt)
plt.savefig("distA-rayleigh.png")

data1 = getData('distB.csv')
stats.probplot(data1, dist = 'norm', plot=plt)
plt.savefig("distB-norm.png")
stats.probplot(data1, dist = 'cauchy', plot=plt)
plt.savefig("distB-cauchy.png")
stats.probplot(data1, dist = 'cosine', plot=plt)
plt.savefig("distB-cosine.png")
stats.probplot(data1, dist = 'expon', plot=plt)
plt.savefig("distB-expon.png")
stats.probplot(data1, dist = 'uniform', plot=plt)
plt.savefig("distB-uniform.png")
stats.probplot(data1, dist = 'laplace', plot=plt)
plt.savefig("distB-laplace.png")
stats.probplot(data1, dist = 'wald', plot=plt)
plt.savefig("distB-wald.png")
stats.probplot(data1, dist = 'rayleigh', plot=plt)
plt.savefig("distB-rayleigh.png")
'''
data2 = getData('distC.csv')
stats.probplot(data2, dist = 'norm', plot=plt)
plt.savefig("distC-norm.png")
stats.probplot(data2, dist = 'cauchy', plot=plt)
plt.savefig("distC-cauchy.png")
stats.probplot(data2, dist = 'cosine', plot=plt)
plt.savefig("distC-cosine.png")
stats.probplot(data2, dist = 'expon', plot=plt)
plt.savefig("distC-expon.png")
stats.probplot(data2, dist = 'uniform', plot=plt)
plt.savefig("distC-uniform.png")
stats.probplot(data2, dist = 'laplace', plot=plt)
plt.savefig("distC-laplace.png")
stats.probplot(data2, dist = 'wald', plot=plt)
plt.savefig("distC-wald.png")
stats.probplot(data2, dist = 'rayleigh', plot=plt)
plt.savefig("distC-rayleigh.png")
